`default_nettype none

module riscv_formal_axi_monitor_template #(
   parameter int unsigned ID_WIDTH = 2,
   parameter int unsigned ADDRESS_WIDTH = 32,
   parameter int unsigned DATA_WIDTH = 32,
   parameter int unsigned AWUSER_WIDTH = 1,
   parameter int unsigned WUSER_WIDTH = 1,
   parameter int unsigned BUSER_WIDTH = 1,
   parameter int unsigned ARUSER_WIDTH = 1,
   parameter int unsigned RUSER_WIDTH = 1,
   parameter int unsigned MAX_WR_BURSTS = 1,
   parameter int unsigned MAX_RD_BURSTS = 1,
   parameter int unsigned MAX_WR_LENGTH = 1,
   parameter int unsigned MAX_RD_LENGTH = 1,
   parameter int unsigned MAXWAIT = 16,
   localparam int unsigned STRB_WIDTH = DATA_WIDTH / 8
) (
   input wire                         clock,
   input wire                         reset,

   input wire [ID_WIDTH-1:0]          axi_aw_id,
   input wire [ADDRESS_WIDTH-1:0]     axi_aw_addr,
   input wire [7:0]                   axi_aw_len,
   input wire [2:0]                   axi_aw_size,
   input wire [1:0]                   axi_aw_burst,
   input wire                         axi_aw_lock,
   input wire [3:0]                   axi_aw_cache,
   input wire [2:0]                   axi_aw_prot,
   input wire [3:0]                   axi_aw_qos,
   input wire [3:0]                   axi_aw_region,
   input wire [AWUSER_WIDTH-1:0]      axi_aw_user,
   input wire                         axi_aw_valid,
   input wire                         axi_aw_ready,

   input wire [DATA_WIDTH-1:0]        axi_w_data,
   input wire [STRB_WIDTH-1:0]        axi_w_strb,
   input wire                         axi_w_last,
   input wire [WUSER_WIDTH-1:0]       axi_w_user,
   input wire                         axi_w_valid,
   input wire                         axi_w_ready,

   input wire [ID_WIDTH-1:0]          axi_b_id,
   input wire [1:0]                   axi_b_resp,
   input wire [BUSER_WIDTH-1:0]       axi_b_user,
   input wire                         axi_b_valid,
   input wire                         axi_b_ready,

   input wire [ID_WIDTH-1:0]          axi_ar_id,
   input wire [ADDRESS_WIDTH-1:0]     axi_ar_addr,
   input wire [7:0]                   axi_ar_len,
   input wire [2:0]                   axi_ar_size,
   input wire [1:0]                   axi_ar_burst,
   input wire                         axi_ar_lock,
   input wire [3:0]                   axi_ar_cache,
   input wire [2:0]                   axi_ar_prot,
   input wire [3:0]                   axi_ar_qos,
   input wire [3:0]                   axi_ar_region,
   input wire [ARUSER_WIDTH-1:0]      axi_ar_user,
   input wire                         axi_ar_valid,
   input wire                         axi_ar_ready,

   input wire [ID_WIDTH-1:0]          axi_r_id,
   input wire [DATA_WIDTH-1:0]        axi_r_data,
   input wire [1:0]                   axi_r_resp,
   input wire                         axi_r_last,
   input wire [RUSER_WIDTH-1:0]       axi_r_user,
   input wire                         axi_r_valid,
   input wire                         axi_r_ready
);

   amba_axi4_monitor_wrapper_oss #(
      .ID_WIDTH(ID_WIDTH),
      .ADDRESS_WIDTH(ADDRESS_WIDTH),
      .DATA_WIDTH(DATA_WIDTH),
      .AWUSER_WIDTH(AWUSER_WIDTH),
      .WUSER_WIDTH(WUSER_WIDTH),
      .BUSER_WIDTH(BUSER_WIDTH),
      .ARUSER_WIDTH(ARUSER_WIDTH),
      .RUSER_WIDTH(RUSER_WIDTH),
      .MAX_WR_BURSTS(MAX_WR_BURSTS),
      .MAX_RD_BURSTS(MAX_RD_BURSTS),
      .MAX_WR_LENGTH(MAX_WR_LENGTH),
      .MAX_RD_LENGTH(MAX_RD_LENGTH),
      .MAXWAIT(MAXWAIT),
      .VERIFY_AGENT_TYPE(amba_axi4_protocol_checker_pkg::MONITOR),
      .PROTOCOL_TYPE(amba_axi4_protocol_checker_pkg::AXI4FULL),
      .INTERFACE_REQS(1'b1),
      .ENABLE_COVER(1'b0),
      .ENABLE_XPROP(1'b0),
      .ARM_RECOMMENDED(1'b0),
      .CHECK_PARAMETERS(1'b1),
      .OPTIONAL_WSTRB(1'b1),
      .FULL_WR_STRB(1'b0),
      .OPTIONAL_RESET(1'b1),
      .FORMAL_INIT_GUARD(1'b1),
      .EXCLUSIVE_ACCESS(1'b0),
      .OPTIONAL_LP(1'b0)
   ) axi_protocol_monitor (
      .ACLK(clock),
      .ARESETn(!reset),

      .AWID(axi_aw_id),
      .AWADDR(axi_aw_addr),
      .AWLEN(axi_aw_len),
      .AWSIZE(axi_aw_size),
      .AWBURST(axi_aw_burst),
      .AWLOCK(axi_aw_lock),
      .AWCACHE(axi_aw_cache),
      .AWPROT(axi_aw_prot),
      .AWQOS(axi_aw_qos),
      .AWREGION(axi_aw_region),
      .AWUSER(axi_aw_user),
      .AWVALID(axi_aw_valid),
      .AWREADY(axi_aw_ready),

      .WDATA(axi_w_data),
      .WSTRB(axi_w_strb),
      .WLAST(axi_w_last),
      .WUSER(axi_w_user),
      .WVALID(axi_w_valid),
      .WREADY(axi_w_ready),

      .BID(axi_b_id),
      .BRESP(axi_b_resp),
      .BUSER(axi_b_user),
      .BVALID(axi_b_valid),
      .BREADY(axi_b_ready),

      .ARID(axi_ar_id),
      .ARADDR(axi_ar_addr),
      .ARLEN(axi_ar_len),
      .ARSIZE(axi_ar_size),
      .ARBURST(axi_ar_burst),
      .ARLOCK(axi_ar_lock),
      .ARCACHE(axi_ar_cache),
      .ARPROT(axi_ar_prot),
      .ARQOS(axi_ar_qos),
      .ARREGION(axi_ar_region),
      .ARUSER(axi_ar_user),
      .ARVALID(axi_ar_valid),
      .ARREADY(axi_ar_ready),

      .RID(axi_r_id),
      .RDATA(axi_r_data),
      .RRESP(axi_r_resp),
      .RLAST(axi_r_last),
      .RUSER(axi_r_user),
      .RVALID(axi_r_valid),
      .RREADY(axi_r_ready),

      .CSYSREQ(1'b0),
      .CSYSACK(1'b0),
      .CACTIVE(1'b0)
   );

endmodule

`default_nettype wire
