// Generated by CIRCT firtool-1.105.0
module CacheBus2Axi4(	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
  input         clock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
                reset,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
  output        io_in_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_in_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [31:0] io_in_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_in_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_in_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [3:0]  io_in_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_in_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [1:0]  io_in_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_in_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_in_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_in_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [31:0] io_in_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_in_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_in_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_aw_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_aw_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [31:0] io_out_aw_bits_awaddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [7:0]  io_out_aw_bits_awlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [2:0]  io_out_aw_bits_awsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_w_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_w_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [31:0] io_out_w_bits_wdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [3:0]  io_out_w_bits_wstrb,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_w_bits_wlast,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_out_b_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_b_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [1:0]  io_out_b_bits_bresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_ar_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_ar_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [31:0] io_out_ar_bits_araddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [7:0]  io_out_ar_bits_arlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [2:0]  io_out_ar_bits_arsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_r_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_r_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [1:0]  io_out_r_bits_rresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [31:0] io_out_r_bits_rdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_r_bits_rlast	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
);

  wire        io_out_b_ready_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:188:47]
  reg  [31:0] reqBuf_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg  [31:0] reqBuf_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg  [3:0]  reqBuf_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg  [3:0]  reqBuf_len;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg  [1:0]  reqBuf_size;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg         reqBuf_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg         reqBufValid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37]
  reg         needAw;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:128:37]
  reg         needW;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:129:37]
  reg         needAr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:130:37]
  reg         writeBurstActive;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:131:37]
  wire        io_out_aw_valid_0 = reqBufValid & needAw;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :133:44]
  wire [7:0]  io_out_ar_bits_arlen_0 = {4'h0, reqBuf_len};	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33, :136:29]
  wire [2:0]  io_out_ar_bits_arsize_0 = {1'h0, reqBuf_size};	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33, :137:29]
  wire        io_out_w_valid_0 = reqBufValid & needW;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :129:37, :143:44]
  wire        io_out_ar_valid_0 = reqBufValid & needAr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :130:37, :148:44]
  wire        _needAwNext_T = io_out_aw_ready & io_out_aw_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:133:44, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _needWNext_T = io_out_w_ready & io_out_w_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:143:44, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _needArNext_T = io_out_ar_ready & io_out_ar_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:148:44, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        reqDone =
    reqBufValid & ~(needAw & ~_needAwNext_T) & ~(needW & ~_needWNext_T)
    & ~(needAr & ~_needArNext_T);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :129:37, :130:37, :158:{37,39}, :159:{36,38}, :160:{37,39}, :161:{42,44,56,58,69,71}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        io_in_req_ready_0 = ~reqBufValid | reqDone;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :161:{42,56,69}, :163:{31,44}]
  reg         rsp_w;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:179:37]
  assign io_out_b_ready_0 = io_in_rsp_ready & rsp_w;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:179:37, :188:47]
  wire        _GEN = io_in_req_ready_0 & io_in_req_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:163:44, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
    if (_GEN) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      reqBuf_addr <= io_in_req_bits_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_data <= io_in_req_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_mask <= io_in_req_bits_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_len <= io_in_req_bits_len;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_size <= io_in_req_bits_size;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_last <= io_in_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
    end
    if (reset) begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
      reqBufValid <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37]
      needAw <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:128:37]
      needW <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:129:37]
      needAr <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:130:37]
      writeBurstActive <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:131:37]
      rsp_w <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:179:37]
    end
    else begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
      reqBufValid <= _GEN | (reqBufValid ? ~reqDone : reqBufValid);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :161:{42,56,69}, :165:27, :167:28, :172:31, :173:{28,31}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      needAw <=
        _GEN
          ? io_in_req_bits_wen & ~writeBurstActive
          : (~reqBufValid | ~_needAwNext_T) & needAw;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :131:37, :158:39, :165:27, :168:{28,50,52}, :172:31, :174:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      needW <= _GEN ? io_in_req_bits_wen : (~reqBufValid | ~_needWNext_T) & needW;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :129:37, :159:38, :165:27, :169:28, :172:31, :174:28, :175:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      needAr <= _GEN ? ~io_in_req_bits_wen : (~reqBufValid | ~_needArNext_T) & needAr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :130:37, :160:39, :165:27, :170:{28,31}, :172:31, :174:28, :176:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (_GEN)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        writeBurstActive <= io_in_req_bits_wen & ~io_in_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:131:37, :171:{50,52}]
      if (_GEN & io_in_req_bits_last)	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:180:26, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        rsp_w <= io_in_req_bits_wen;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:179:37]
    end
  end // always @(posedge)
  assign io_in_req_ready = io_in_req_ready_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :163:44]
  assign io_in_rsp_valid = rsp_w ? io_out_b_valid : io_out_r_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :179:37, :183:35]
  assign io_in_rsp_bits_data = io_out_r_bits_rdata;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
  assign io_in_rsp_bits_last = io_out_r_bits_rlast | io_out_b_ready_0 & io_out_b_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :186:52, :188:47, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_in_rsp_bits_err = rsp_w ? io_out_b_bits_bresp[0] : io_out_r_bits_rresp[0];	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :119:16, :179:37, :184:35]
  assign io_out_aw_valid = io_out_aw_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :133:44]
  assign io_out_aw_bits_awaddr = reqBuf_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_aw_bits_awlen = io_out_ar_bits_arlen_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :136:29]
  assign io_out_aw_bits_awsize = io_out_ar_bits_arsize_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :137:29]
  assign io_out_w_valid = io_out_w_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :143:44]
  assign io_out_w_bits_wdata = reqBuf_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_w_bits_wstrb = reqBuf_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_w_bits_wlast = reqBuf_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_b_ready = io_out_b_ready_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :188:47]
  assign io_out_ar_valid = io_out_ar_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :148:44]
  assign io_out_ar_bits_araddr = reqBuf_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_ar_bits_arlen = io_out_ar_bits_arlen_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :136:29]
  assign io_out_ar_bits_arsize = io_out_ar_bits_arsize_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :137:29]
  assign io_out_r_ready = io_in_rsp_ready & ~rsp_w;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :179:37, :189:{47,49}]
endmodule

module CacheBus2Axi4Top(	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7]
  input         clock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7]
                reset,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7]
  output        io_in_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input         io_in_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input  [31:0] io_in_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
                io_in_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input         io_in_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
                io_in_req_bits_burst,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input  [3:0]  io_in_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
                io_in_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input  [1:0]  io_in_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input         io_in_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
                io_in_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output        io_in_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [31:0] io_in_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output        io_in_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
                io_in_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input         io_out_aw_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output        io_out_aw_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [31:0] io_out_aw_bits_awaddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [1:0]  io_out_aw_bits_awid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [7:0]  io_out_aw_bits_awlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [2:0]  io_out_aw_bits_awsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [1:0]  io_out_aw_bits_awburst,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output        io_out_aw_bits_awlock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [3:0]  io_out_aw_bits_awcache,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [2:0]  io_out_aw_bits_awprot,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input         io_out_w_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output        io_out_w_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [31:0] io_out_w_bits_wdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [3:0]  io_out_w_bits_wstrb,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output        io_out_w_bits_wlast,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
                io_out_b_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input         io_out_b_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input  [1:0]  io_out_b_bits_bresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
                io_out_b_bits_bid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input         io_out_ar_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output        io_out_ar_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [31:0] io_out_ar_bits_araddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [1:0]  io_out_ar_bits_arid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [7:0]  io_out_ar_bits_arlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [2:0]  io_out_ar_bits_arsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [1:0]  io_out_ar_bits_arburst,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output        io_out_ar_bits_arlock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [3:0]  io_out_ar_bits_arcache,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output [2:0]  io_out_ar_bits_arprot,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  output        io_out_r_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input         io_out_r_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input  [1:0]  io_out_r_bits_rresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input  [31:0] io_out_r_bits_rdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input         io_out_r_bits_rlast,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
  input  [1:0]  io_out_r_bits_rid	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:7:14]
);

  CacheBus2Axi4 bridge (	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:12:22]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_req_ready       (io_in_req_ready),
    .io_in_req_valid       (io_in_req_valid),
    .io_in_req_bits_addr   (io_in_req_bits_addr),
    .io_in_req_bits_data   (io_in_req_bits_data),
    .io_in_req_bits_wen    (io_in_req_bits_wen),
    .io_in_req_bits_mask   (io_in_req_bits_mask),
    .io_in_req_bits_len    (io_in_req_bits_len),
    .io_in_req_bits_size   (io_in_req_bits_size),
    .io_in_req_bits_last   (io_in_req_bits_last),
    .io_in_rsp_ready       (io_in_rsp_ready),
    .io_in_rsp_valid       (io_in_rsp_valid),
    .io_in_rsp_bits_data   (io_in_rsp_bits_data),
    .io_in_rsp_bits_last   (io_in_rsp_bits_last),
    .io_in_rsp_bits_err    (io_in_rsp_bits_err),
    .io_out_aw_ready       (io_out_aw_ready),
    .io_out_aw_valid       (io_out_aw_valid),
    .io_out_aw_bits_awaddr (io_out_aw_bits_awaddr),
    .io_out_aw_bits_awlen  (io_out_aw_bits_awlen),
    .io_out_aw_bits_awsize (io_out_aw_bits_awsize),
    .io_out_w_ready        (io_out_w_ready),
    .io_out_w_valid        (io_out_w_valid),
    .io_out_w_bits_wdata   (io_out_w_bits_wdata),
    .io_out_w_bits_wstrb   (io_out_w_bits_wstrb),
    .io_out_w_bits_wlast   (io_out_w_bits_wlast),
    .io_out_b_ready        (io_out_b_ready),
    .io_out_b_valid        (io_out_b_valid),
    .io_out_b_bits_bresp   (io_out_b_bits_bresp),
    .io_out_ar_ready       (io_out_ar_ready),
    .io_out_ar_valid       (io_out_ar_valid),
    .io_out_ar_bits_araddr (io_out_ar_bits_araddr),
    .io_out_ar_bits_arlen  (io_out_ar_bits_arlen),
    .io_out_ar_bits_arsize (io_out_ar_bits_arsize),
    .io_out_r_ready        (io_out_r_ready),
    .io_out_r_valid        (io_out_r_valid),
    .io_out_r_bits_rresp   (io_out_r_bits_rresp),
    .io_out_r_bits_rdata   (io_out_r_bits_rdata),
    .io_out_r_bits_rlast   (io_out_r_bits_rlast)
  );	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:12:22]
  assign io_out_aw_bits_awid = 2'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
  assign io_out_aw_bits_awburst = 2'h1;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
  assign io_out_aw_bits_awlock = 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
  assign io_out_aw_bits_awcache = 4'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
  assign io_out_aw_bits_awprot = 3'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
  assign io_out_ar_bits_arid = 2'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
  assign io_out_ar_bits_arburst = 2'h1;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
  assign io_out_ar_bits_arlock = 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
  assign io_out_ar_bits_arcache = 4'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
  assign io_out_ar_bits_arprot = 3'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:6:7, :12:22]
endmodule
