// Generated by CIRCT firtool-1.105.0
module CacheBusCrossbarNto1(	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
  input         clock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
                reset,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
  output        io_in_0_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input         io_in_0_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input  [31:0] io_in_0_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_in_0_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input         io_in_0_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input  [3:0]  io_in_0_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_in_0_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input  [1:0]  io_in_0_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input         io_in_0_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_in_0_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output        io_in_0_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output [31:0] io_in_0_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output        io_in_0_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_in_0_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_in_1_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input         io_in_1_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input  [31:0] io_in_1_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_in_1_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input         io_in_1_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input  [3:0]  io_in_1_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_in_1_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input  [1:0]  io_in_1_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input         io_in_1_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_in_1_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output        io_in_1_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output [31:0] io_in_1_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output        io_in_1_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_in_1_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input         io_out_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output        io_out_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output [31:0] io_out_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_out_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output        io_out_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output [3:0]  io_out_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_out_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output [1:0]  io_out_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  output        io_out_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_out_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input         io_out_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input  [31:0] io_out_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
  input         io_out_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
                io_out_rsp_bits_err	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:125:16]
);

  reg  [1:0] st;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:139:26]
  wire       st_is_idle = st == 2'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:139:26, :141:27]
  wire       st_is_locked = st == 2'h1;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:139:26, :142:28]
  wire       InputSelVec_1 = io_in_1_req_valid & ~io_in_0_req_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:132:70, :147:89]
  reg        InputSelReg_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:148:32]
  reg        InputSelReg_1;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:148:32]
  wire       _io_out_req_bits_T = io_in_0_req_valid & io_in_0_req_bits_last;	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
  wire       _io_out_req_bits_T_1 = InputSelVec_1 & io_in_1_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:147:89, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire       _io_out_req_bits_T_24 = InputSelReg_0 & io_in_0_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:148:32, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire       _io_out_req_bits_T_25 = InputSelReg_1 & io_in_1_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:148:32, src/main/scala/chisel3/util/Mux.scala:30:73]
  reg  [1:0] casez_tmp;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:153:16, :156:19]
  always_comb begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:137:25, :141:27, :142:28, :143:27, :153:16, :156:19, :160:19, :164:19]
    casez (st)	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:137:25, :139:26, :141:27, :142:28, :143:27, :153:16, :156:19, :160:19, :164:19]
      2'b00:
        casez_tmp = _io_out_req_bits_T | _io_out_req_bits_T_1 ? 2'h2 : 2'h1;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:137:25, :141:27, :142:28, :143:27, :153:16, :156:{19,25}, :160:19, :164:19, src/main/scala/chisel3/util/Mux.scala:30:73]
      2'b01:
        casez_tmp = _io_out_req_bits_T_24 | _io_out_req_bits_T_25 ? 2'h2 : 2'h1;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:137:25, :141:27, :142:28, :143:27, :153:16, :156:19, :160:{19,25}, :164:19, src/main/scala/chisel3/util/Mux.scala:30:73]
      2'b10:
        casez_tmp = {~io_out_rsp_bits_last, 1'h0};	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:137:25, :141:27, :142:28, :143:27, :153:16, :156:19, :160:19, :164:{19,25}]
      default:
        casez_tmp = 2'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:137:25, :141:27, :142:28, :143:27, :153:16, :156:19, :160:19, :164:19]
    endcase	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:137:25, :139:26, :141:27, :142:28, :143:27, :153:16, :156:19, :160:19, :164:19]
  end // always_comb
  wire       io_out_req_valid_0 =
    st_is_idle & (|{io_in_1_req_valid, io_in_0_req_valid}) | st_is_locked
    & (InputSelReg_0 & io_in_0_req_valid | InputSelReg_1 & io_in_1_req_valid);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:141:27, :142:28, :148:32, :169:{36,50,57,61,76}, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire       _io_out_rsp_ready_T_2 =
    InputSelReg_0 & io_in_0_rsp_ready | InputSelReg_1 & io_in_1_rsp_ready;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:148:32, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire       _st_en_T_1 = io_out_req_ready & io_out_req_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:169:61, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
    if (reset) begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
      st <= 2'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:139:26]
      InputSelReg_0 <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:148:32]
      InputSelReg_1 <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:148:32]
    end
    else begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
      if (st_is_idle | st_is_locked
            ? _st_en_T_1
            : st == 2'h2 & _io_out_rsp_ready_T_2 & io_out_rsp_valid)	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:138:25, :139:26, :141:27, :142:28, :143:27, :153:16, :155:19, :159:19, :163:19, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:30:73]
        st <= casez_tmp;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:139:26, :153:16, :156:19]
      if (_st_en_T_1 & st_is_idle) begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:141:27, :148:110, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        InputSelReg_0 <= io_in_0_req_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:148:32]
        InputSelReg_1 <= InputSelVec_1;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:147:89, :148:32]
      end
    end
  end // always @(posedge)
  assign io_in_0_req_ready =
    io_out_req_ready & st_is_idle | InputSelReg_0 & io_out_req_ready & st_is_locked;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :141:27, :142:28, :148:32, :178:{65,78}, :179:{46,65}]
  assign io_in_0_rsp_valid = InputSelReg_0 & io_out_rsp_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :148:32, :183:46]
  assign io_in_0_rsp_bits_data = io_out_rsp_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
  assign io_in_0_rsp_bits_last = io_out_rsp_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
  assign io_in_0_rsp_bits_err = io_out_rsp_bits_err;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
  assign io_in_1_req_ready =
    ~io_in_0_req_valid & io_out_req_ready & st_is_idle | InputSelReg_1 & io_out_req_ready
    & st_is_locked;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :132:70, :141:27, :142:28, :148:32, :178:{46,65,78}, :179:{46,65}]
  assign io_in_1_rsp_valid = InputSelReg_1 & io_out_rsp_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :148:32, :183:46]
  assign io_in_1_rsp_bits_data = io_out_rsp_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
  assign io_in_1_rsp_bits_last = io_out_rsp_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
  assign io_in_1_rsp_bits_err = io_out_rsp_bits_err;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7]
  assign io_out_req_valid = io_out_req_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :169:61]
  assign io_out_req_bits_addr =
    st_is_idle
      ? (io_in_0_req_valid ? io_in_0_req_bits_addr : 32'h0)
        | (InputSelVec_1 ? io_in_1_req_bits_addr : 32'h0)
      : (InputSelReg_0 ? io_in_0_req_bits_addr : 32'h0)
        | (InputSelReg_1 ? io_in_1_req_bits_addr : 32'h0);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :141:27, :147:89, :148:32, :171:23, :172:25, :174:25, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_out_req_bits_data =
    st_is_idle
      ? (io_in_0_req_valid ? io_in_0_req_bits_data : 32'h0)
        | (InputSelVec_1 ? io_in_1_req_bits_data : 32'h0)
      : (InputSelReg_0 ? io_in_0_req_bits_data : 32'h0)
        | (InputSelReg_1 ? io_in_1_req_bits_data : 32'h0);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :141:27, :147:89, :148:32, :171:23, :172:25, :174:25, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_out_req_bits_wen =
    st_is_idle
      ? io_in_0_req_valid & io_in_0_req_bits_wen | InputSelVec_1 & io_in_1_req_bits_wen
      : InputSelReg_0 & io_in_0_req_bits_wen | InputSelReg_1 & io_in_1_req_bits_wen;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :141:27, :147:89, :148:32, :171:23, :172:25, :174:25, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_out_req_bits_mask =
    st_is_idle
      ? (io_in_0_req_valid ? io_in_0_req_bits_mask : 4'h0)
        | (InputSelVec_1 ? io_in_1_req_bits_mask : 4'h0)
      : (InputSelReg_0 ? io_in_0_req_bits_mask : 4'h0)
        | (InputSelReg_1 ? io_in_1_req_bits_mask : 4'h0);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :141:27, :147:89, :148:32, :171:23, :172:25, :174:25, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_out_req_bits_len =
    st_is_idle
      ? (io_in_0_req_valid ? io_in_0_req_bits_len : 4'h0)
        | (InputSelVec_1 ? io_in_1_req_bits_len : 4'h0)
      : (InputSelReg_0 ? io_in_0_req_bits_len : 4'h0)
        | (InputSelReg_1 ? io_in_1_req_bits_len : 4'h0);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :141:27, :147:89, :148:32, :171:23, :172:25, :174:25, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_out_req_bits_size =
    st_is_idle
      ? (io_in_0_req_valid ? io_in_0_req_bits_size : 2'h0)
        | (InputSelVec_1 ? io_in_1_req_bits_size : 2'h0)
      : (InputSelReg_0 ? io_in_0_req_bits_size : 2'h0)
        | (InputSelReg_1 ? io_in_1_req_bits_size : 2'h0);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :141:27, :147:89, :148:32, :171:23, :172:25, :174:25, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_out_req_bits_last =
    st_is_idle
      ? _io_out_req_bits_T | _io_out_req_bits_T_1
      : _io_out_req_bits_T_24 | _io_out_req_bits_T_25;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, :141:27, :171:23, :172:25, :174:25, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_out_rsp_ready = _io_out_rsp_ready_T_2;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:124:7, src/main/scala/chisel3/util/Mux.scala:30:73]
endmodule

module CacheBus2Axi4(	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
  input         clock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
                reset,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
  output        io_in_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_in_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [31:0] io_in_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_in_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_in_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [3:0]  io_in_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_in_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [1:0]  io_in_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_in_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_in_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_in_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [31:0] io_in_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_in_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_in_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_aw_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_aw_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [31:0] io_out_aw_bits_awaddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [7:0]  io_out_aw_bits_awlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [2:0]  io_out_aw_bits_awsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_w_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_w_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [31:0] io_out_w_bits_wdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [3:0]  io_out_w_bits_wstrb,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_w_bits_wlast,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
                io_out_b_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_b_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [1:0]  io_out_b_bits_bresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_ar_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_ar_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [31:0] io_out_ar_bits_araddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [7:0]  io_out_ar_bits_arlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output [2:0]  io_out_ar_bits_arsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  output        io_out_r_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_r_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [1:0]  io_out_r_bits_rresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input  [31:0] io_out_r_bits_rdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
  input         io_out_r_bits_rlast	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:119:16]
);

  wire        io_out_b_ready_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:188:47]
  reg  [31:0] reqBuf_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg  [31:0] reqBuf_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg  [3:0]  reqBuf_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg  [3:0]  reqBuf_len;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg  [1:0]  reqBuf_size;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg         reqBuf_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
  reg         reqBufValid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37]
  reg         needAw;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:128:37]
  reg         needW;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:129:37]
  reg         needAr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:130:37]
  reg         writeBurstActive;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:131:37]
  wire        io_out_aw_valid_0 = reqBufValid & needAw;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :133:44]
  wire [7:0]  io_out_ar_bits_arlen_0 = {4'h0, reqBuf_len};	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33, :136:29]
  wire [2:0]  io_out_ar_bits_arsize_0 = {1'h0, reqBuf_size};	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33, :137:29]
  wire        io_out_w_valid_0 = reqBufValid & needW;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :129:37, :143:44]
  wire        io_out_ar_valid_0 = reqBufValid & needAr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :130:37, :148:44]
  wire        _needAwNext_T = io_out_aw_ready & io_out_aw_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:133:44, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _needWNext_T = io_out_w_ready & io_out_w_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:143:44, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _needArNext_T = io_out_ar_ready & io_out_ar_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:148:44, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        reqDone =
    reqBufValid & ~(needAw & ~_needAwNext_T) & ~(needW & ~_needWNext_T)
    & ~(needAr & ~_needArNext_T);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :129:37, :130:37, :158:{37,39}, :159:{36,38}, :160:{37,39}, :161:{42,44,56,58,69,71}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        io_in_req_ready_0 = ~reqBufValid | reqDone;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :161:{42,56,69}, :163:{31,44}]
  reg         rsp_w;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:179:37]
  assign io_out_b_ready_0 = io_in_rsp_ready & rsp_w;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:179:37, :188:47]
  wire        _GEN = io_in_req_ready_0 & io_in_req_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:163:44, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
    if (_GEN) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      reqBuf_addr <= io_in_req_bits_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_data <= io_in_req_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_mask <= io_in_req_bits_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_len <= io_in_req_bits_len;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_size <= io_in_req_bits_size;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
      reqBuf_last <= io_in_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:126:33]
    end
    if (reset) begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
      reqBufValid <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37]
      needAw <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:128:37]
      needW <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:129:37]
      needAr <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:130:37]
      writeBurstActive <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:131:37]
      rsp_w <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:179:37]
    end
    else begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
      reqBufValid <= _GEN | (reqBufValid ? ~reqDone : reqBufValid);	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :161:{42,56,69}, :165:27, :167:28, :172:31, :173:{28,31}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      needAw <=
        _GEN
          ? io_in_req_bits_wen & ~writeBurstActive
          : (~reqBufValid | ~_needAwNext_T) & needAw;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :131:37, :158:39, :165:27, :168:{28,50,52}, :172:31, :174:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      needW <= _GEN ? io_in_req_bits_wen : (~reqBufValid | ~_needWNext_T) & needW;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :129:37, :159:38, :165:27, :169:28, :172:31, :174:28, :175:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      needAr <= _GEN ? ~io_in_req_bits_wen : (~reqBufValid | ~_needArNext_T) & needAr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:127:37, :128:37, :130:37, :160:39, :165:27, :170:{28,31}, :172:31, :174:28, :176:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (_GEN)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        writeBurstActive <= io_in_req_bits_wen & ~io_in_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:131:37, :171:{50,52}]
      if (_GEN & io_in_req_bits_last)	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:180:26, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        rsp_w <= io_in_req_bits_wen;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:179:37]
    end
  end // always @(posedge)
  assign io_in_req_ready = io_in_req_ready_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :163:44]
  assign io_in_rsp_valid = rsp_w ? io_out_b_valid : io_out_r_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :179:37, :183:35]
  assign io_in_rsp_bits_data = io_out_r_bits_rdata;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7]
  assign io_in_rsp_bits_last = io_out_r_bits_rlast | io_out_b_ready_0 & io_out_b_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :186:52, :188:47, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign io_in_rsp_bits_err = rsp_w ? io_out_b_bits_bresp[0] : io_out_r_bits_rresp[0];	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :119:16, :179:37, :184:35]
  assign io_out_aw_valid = io_out_aw_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :133:44]
  assign io_out_aw_bits_awaddr = reqBuf_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_aw_bits_awlen = io_out_ar_bits_arlen_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :136:29]
  assign io_out_aw_bits_awsize = io_out_ar_bits_arsize_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :137:29]
  assign io_out_w_valid = io_out_w_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :143:44]
  assign io_out_w_bits_wdata = reqBuf_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_w_bits_wstrb = reqBuf_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_w_bits_wlast = reqBuf_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_b_ready = io_out_b_ready_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :188:47]
  assign io_out_ar_valid = io_out_ar_valid_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :148:44]
  assign io_out_ar_bits_araddr = reqBuf_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :126:33]
  assign io_out_ar_bits_arlen = io_out_ar_bits_arlen_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :136:29]
  assign io_out_ar_bits_arsize = io_out_ar_bits_arsize_0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :137:29]
  assign io_out_r_ready = io_in_rsp_ready & ~rsp_w;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/AXI4Bundle.scala:118:7, :179:37, :189:{47,49}]
endmodule

module CacheBusCut(	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7]
  input         clock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7]
                reset,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7]
  output        io_in_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input         io_in_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input  [31:0] io_in_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
                io_in_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input         io_in_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input  [3:0]  io_in_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
                io_in_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input  [1:0]  io_in_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input         io_in_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
                io_in_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  output        io_in_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  output [31:0] io_in_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  output        io_in_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
                io_in_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input         io_out_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  output        io_out_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  output [31:0] io_out_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
                io_out_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  output        io_out_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  output [3:0]  io_out_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
                io_out_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  output [1:0]  io_out_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  output        io_out_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
                io_out_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input         io_out_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input  [31:0] io_out_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
  input         io_out_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
                io_out_rsp_bits_err	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:49:14]
);

  reg         io_out_req_vld;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56]
  reg  [31:0] io_out_req_data_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  reg  [31:0] io_out_req_data_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  reg         io_out_req_data_wen;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  reg  [3:0]  io_out_req_data_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  reg  [3:0]  io_out_req_data_len;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  reg  [1:0]  io_out_req_data_size;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  reg         io_out_req_data_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  reg         io_in_rsp_vld;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56]
  reg  [31:0] io_in_rsp_data_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  reg         io_in_rsp_data_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  reg         io_in_rsp_data_err;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  wire        io_out_req_vld_set = ~io_out_req_vld & io_in_req_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56, :49:70, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        io_out_req_vld_clr = io_out_req_ready & io_out_req_vld;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        io_in_rsp_vld_set = ~io_in_rsp_vld & io_out_rsp_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56, :49:70, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        io_in_rsp_vld_clr = io_in_rsp_ready & io_in_rsp_vld;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7]
    if (reset) begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7]
      io_out_req_vld <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56]
      io_out_req_data_addr <= 32'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      io_out_req_data_data <= 32'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      io_out_req_data_wen <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      io_out_req_data_mask <= 4'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      io_out_req_data_len <= 4'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      io_out_req_data_size <= 2'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      io_out_req_data_last <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      io_in_rsp_vld <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56]
      io_in_rsp_data_data <= 32'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      io_in_rsp_data_last <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      io_in_rsp_data_err <= 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
    end
    else begin	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7]
      if (io_out_req_vld_set | io_out_req_vld_clr)	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:42:55, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        io_out_req_vld <= io_out_req_vld_set | ~io_out_req_vld_clr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:43:{55,57}, :44:56, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (io_out_req_vld_set) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        io_out_req_data_addr <= io_in_req_bits_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
        io_out_req_data_data <= io_in_req_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
        io_out_req_data_wen <= io_in_req_bits_wen;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
        io_out_req_data_mask <= io_in_req_bits_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
        io_out_req_data_len <= io_in_req_bits_len;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
        io_out_req_data_size <= io_in_req_bits_size;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
        io_out_req_data_last <= io_in_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      end
      if (io_in_rsp_vld_set | io_in_rsp_vld_clr)	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:42:55, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        io_in_rsp_vld <= io_in_rsp_vld_set | ~io_in_rsp_vld_clr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:43:{55,57}, :44:56, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (io_in_rsp_vld_set) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        io_in_rsp_data_data <= io_out_rsp_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
        io_in_rsp_data_last <= io_out_rsp_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
        io_in_rsp_data_err <= io_out_rsp_bits_err;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
      end
    end
  end // always @(posedge)
  assign io_in_req_ready = ~io_out_req_vld;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56, :49:70]
  assign io_in_rsp_valid = io_in_rsp_vld;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56]
  assign io_in_rsp_bits_data = io_in_rsp_data_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_in_rsp_bits_last = io_in_rsp_data_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_in_rsp_bits_err = io_in_rsp_data_err;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_out_req_valid = io_out_req_vld;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56]
  assign io_out_req_bits_addr = io_out_req_data_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_out_req_bits_data = io_out_req_data_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_out_req_bits_wen = io_out_req_data_wen;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_out_req_bits_mask = io_out_req_data_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_out_req_bits_len = io_out_req_data_len;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_out_req_bits_size = io_out_req_data_size;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_out_req_bits_last = io_out_req_data_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:45:56]
  assign io_out_rsp_ready = ~io_in_rsp_vld;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SimpleBus.scala:48:7, home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/SpillReg.scala:44:56, :49:70]
endmodule

module crossbarCache(	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:191:7]
  input         clock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:191:7]
                reset,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:191:7]
  output        io_in_0_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_in_0_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input  [31:0] io_in_0_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_in_0_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_in_0_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input  [3:0]  io_in_0_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_in_0_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input  [1:0]  io_in_0_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_in_0_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_in_0_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output        io_in_0_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [31:0] io_in_0_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output        io_in_0_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_in_0_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_in_1_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_in_1_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input  [31:0] io_in_1_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_in_1_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_in_1_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input  [3:0]  io_in_1_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_in_1_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input  [1:0]  io_in_1_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_in_1_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_in_1_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output        io_in_1_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [31:0] io_in_1_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output        io_in_1_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_in_1_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_out_aw_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output        io_out_aw_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [31:0] io_out_aw_bits_awaddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [7:0]  io_out_aw_bits_awlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [2:0]  io_out_aw_bits_awsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_out_w_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output        io_out_w_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [31:0] io_out_w_bits_wdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [3:0]  io_out_w_bits_wstrb,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output        io_out_w_bits_wlast,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
                io_out_b_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_out_b_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input  [1:0]  io_out_b_bits_bresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_out_ar_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output        io_out_ar_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [31:0] io_out_ar_bits_araddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [7:0]  io_out_ar_bits_arlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output [2:0]  io_out_ar_bits_arsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  output        io_out_r_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_out_r_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input  [1:0]  io_out_r_bits_rresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input  [31:0] io_out_r_bits_rdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
  input         io_out_r_bits_rlast	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:192:16]
);

  wire        _buscut_io_in_req_ready;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire        _buscut_io_in_rsp_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire [31:0] _buscut_io_in_rsp_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire        _buscut_io_in_rsp_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire        _buscut_io_in_rsp_bits_err;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire        _buscut_io_out_req_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire [31:0] _buscut_io_out_req_bits_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire [31:0] _buscut_io_out_req_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire        _buscut_io_out_req_bits_wen;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire [3:0]  _buscut_io_out_req_bits_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire [3:0]  _buscut_io_out_req_bits_len;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire [1:0]  _buscut_io_out_req_bits_size;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire        _buscut_io_out_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire        _buscut_io_out_rsp_ready;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  wire        _bridge_io_in_req_ready;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
  wire        _bridge_io_in_rsp_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
  wire [31:0] _bridge_io_in_rsp_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
  wire        _bridge_io_in_rsp_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
  wire        _bridge_io_in_rsp_bits_err;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
  wire        _arbiter_io_out_req_valid;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  wire [31:0] _arbiter_io_out_req_bits_addr;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  wire [31:0] _arbiter_io_out_req_bits_data;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  wire        _arbiter_io_out_req_bits_wen;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  wire [3:0]  _arbiter_io_out_req_bits_mask;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  wire [3:0]  _arbiter_io_out_req_bits_len;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  wire [1:0]  _arbiter_io_out_req_bits_size;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  wire        _arbiter_io_out_req_bits_last;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  wire        _arbiter_io_out_rsp_ready;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  CacheBusCrossbarNto1 arbiter (	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_0_req_ready     (io_in_0_req_ready),
    .io_in_0_req_valid     (io_in_0_req_valid),
    .io_in_0_req_bits_addr (io_in_0_req_bits_addr),
    .io_in_0_req_bits_data (io_in_0_req_bits_data),
    .io_in_0_req_bits_wen  (io_in_0_req_bits_wen),
    .io_in_0_req_bits_mask (io_in_0_req_bits_mask),
    .io_in_0_req_bits_len  (io_in_0_req_bits_len),
    .io_in_0_req_bits_size (io_in_0_req_bits_size),
    .io_in_0_req_bits_last (io_in_0_req_bits_last),
    .io_in_0_rsp_ready     (io_in_0_rsp_ready),
    .io_in_0_rsp_valid     (io_in_0_rsp_valid),
    .io_in_0_rsp_bits_data (io_in_0_rsp_bits_data),
    .io_in_0_rsp_bits_last (io_in_0_rsp_bits_last),
    .io_in_0_rsp_bits_err  (io_in_0_rsp_bits_err),
    .io_in_1_req_ready     (io_in_1_req_ready),
    .io_in_1_req_valid     (io_in_1_req_valid),
    .io_in_1_req_bits_addr (io_in_1_req_bits_addr),
    .io_in_1_req_bits_data (io_in_1_req_bits_data),
    .io_in_1_req_bits_wen  (io_in_1_req_bits_wen),
    .io_in_1_req_bits_mask (io_in_1_req_bits_mask),
    .io_in_1_req_bits_len  (io_in_1_req_bits_len),
    .io_in_1_req_bits_size (io_in_1_req_bits_size),
    .io_in_1_req_bits_last (io_in_1_req_bits_last),
    .io_in_1_rsp_ready     (io_in_1_rsp_ready),
    .io_in_1_rsp_valid     (io_in_1_rsp_valid),
    .io_in_1_rsp_bits_data (io_in_1_rsp_bits_data),
    .io_in_1_rsp_bits_last (io_in_1_rsp_bits_last),
    .io_in_1_rsp_bits_err  (io_in_1_rsp_bits_err),
    .io_out_req_ready      (_buscut_io_in_req_ready),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_out_req_valid      (_arbiter_io_out_req_valid),
    .io_out_req_bits_addr  (_arbiter_io_out_req_bits_addr),
    .io_out_req_bits_data  (_arbiter_io_out_req_bits_data),
    .io_out_req_bits_wen   (_arbiter_io_out_req_bits_wen),
    .io_out_req_bits_mask  (_arbiter_io_out_req_bits_mask),
    .io_out_req_bits_len   (_arbiter_io_out_req_bits_len),
    .io_out_req_bits_size  (_arbiter_io_out_req_bits_size),
    .io_out_req_bits_last  (_arbiter_io_out_req_bits_last),
    .io_out_rsp_ready      (_arbiter_io_out_rsp_ready),
    .io_out_rsp_valid      (_buscut_io_in_rsp_valid),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_out_rsp_bits_data  (_buscut_io_in_rsp_bits_data),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_out_rsp_bits_last  (_buscut_io_in_rsp_bits_last),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_out_rsp_bits_err   (_buscut_io_in_rsp_bits_err)	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
  );	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
  CacheBus2Axi4 bridge (	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_req_ready       (_bridge_io_in_req_ready),
    .io_in_req_valid       (_buscut_io_out_req_valid),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_in_req_bits_addr   (_buscut_io_out_req_bits_addr),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_in_req_bits_data   (_buscut_io_out_req_bits_data),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_in_req_bits_wen    (_buscut_io_out_req_bits_wen),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_in_req_bits_mask   (_buscut_io_out_req_bits_mask),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_in_req_bits_len    (_buscut_io_out_req_bits_len),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_in_req_bits_size   (_buscut_io_out_req_bits_size),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_in_req_bits_last   (_buscut_io_out_req_bits_last),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_in_rsp_ready       (_buscut_io_out_rsp_ready),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .io_in_rsp_valid       (_bridge_io_in_rsp_valid),
    .io_in_rsp_bits_data   (_bridge_io_in_rsp_bits_data),
    .io_in_rsp_bits_last   (_bridge_io_in_rsp_bits_last),
    .io_in_rsp_bits_err    (_bridge_io_in_rsp_bits_err),
    .io_out_aw_ready       (io_out_aw_ready),
    .io_out_aw_valid       (io_out_aw_valid),
    .io_out_aw_bits_awaddr (io_out_aw_bits_awaddr),
    .io_out_aw_bits_awlen  (io_out_aw_bits_awlen),
    .io_out_aw_bits_awsize (io_out_aw_bits_awsize),
    .io_out_w_ready        (io_out_w_ready),
    .io_out_w_valid        (io_out_w_valid),
    .io_out_w_bits_wdata   (io_out_w_bits_wdata),
    .io_out_w_bits_wstrb   (io_out_w_bits_wstrb),
    .io_out_w_bits_wlast   (io_out_w_bits_wlast),
    .io_out_b_ready        (io_out_b_ready),
    .io_out_b_valid        (io_out_b_valid),
    .io_out_b_bits_bresp   (io_out_b_bits_bresp),
    .io_out_ar_ready       (io_out_ar_ready),
    .io_out_ar_valid       (io_out_ar_valid),
    .io_out_ar_bits_araddr (io_out_ar_bits_araddr),
    .io_out_ar_bits_arlen  (io_out_ar_bits_arlen),
    .io_out_ar_bits_arsize (io_out_ar_bits_arsize),
    .io_out_r_ready        (io_out_r_ready),
    .io_out_r_valid        (io_out_r_valid),
    .io_out_r_bits_rresp   (io_out_r_bits_rresp),
    .io_out_r_bits_rdata   (io_out_r_bits_rdata),
    .io_out_r_bits_rlast   (io_out_r_bits_rlast)
  );	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
  CacheBusCut buscut (	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_req_ready      (_buscut_io_in_req_ready),
    .io_in_req_valid      (_arbiter_io_out_req_valid),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .io_in_req_bits_addr  (_arbiter_io_out_req_bits_addr),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .io_in_req_bits_data  (_arbiter_io_out_req_bits_data),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .io_in_req_bits_wen   (_arbiter_io_out_req_bits_wen),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .io_in_req_bits_mask  (_arbiter_io_out_req_bits_mask),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .io_in_req_bits_len   (_arbiter_io_out_req_bits_len),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .io_in_req_bits_size  (_arbiter_io_out_req_bits_size),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .io_in_req_bits_last  (_arbiter_io_out_req_bits_last),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .io_in_rsp_ready      (_arbiter_io_out_rsp_ready),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:197:29]
    .io_in_rsp_valid      (_buscut_io_in_rsp_valid),
    .io_in_rsp_bits_data  (_buscut_io_in_rsp_bits_data),
    .io_in_rsp_bits_last  (_buscut_io_in_rsp_bits_last),
    .io_in_rsp_bits_err   (_buscut_io_in_rsp_bits_err),
    .io_out_req_ready     (_bridge_io_in_req_ready),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
    .io_out_req_valid     (_buscut_io_out_req_valid),
    .io_out_req_bits_addr (_buscut_io_out_req_bits_addr),
    .io_out_req_bits_data (_buscut_io_out_req_bits_data),
    .io_out_req_bits_wen  (_buscut_io_out_req_bits_wen),
    .io_out_req_bits_mask (_buscut_io_out_req_bits_mask),
    .io_out_req_bits_len  (_buscut_io_out_req_bits_len),
    .io_out_req_bits_size (_buscut_io_out_req_bits_size),
    .io_out_req_bits_last (_buscut_io_out_req_bits_last),
    .io_out_rsp_ready     (_buscut_io_out_rsp_ready),
    .io_out_rsp_valid     (_bridge_io_in_rsp_valid),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
    .io_out_rsp_bits_data (_bridge_io_in_rsp_bits_data),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
    .io_out_rsp_bits_last (_bridge_io_in_rsp_bits_last),	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
    .io_out_rsp_bits_err  (_bridge_io_in_rsp_bits_err)	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:198:29]
  );	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/Crossbar.scala:199:25]
endmodule

module CrossbarCacheTop(	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7]
  input         clock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7]
                reset,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7]
  output        io_in_0_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_in_0_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [31:0] io_in_0_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_0_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_in_0_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_0_req_bits_burst,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [3:0]  io_in_0_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_0_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [1:0]  io_in_0_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_in_0_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_0_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_in_0_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [31:0] io_in_0_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_in_0_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_0_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_1_req_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_in_1_req_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [31:0] io_in_1_req_bits_addr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_1_req_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_in_1_req_bits_wen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_1_req_bits_burst,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [3:0]  io_in_1_req_bits_mask,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_1_req_bits_len,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [1:0]  io_in_1_req_bits_size,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_in_1_req_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_1_rsp_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_in_1_rsp_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [31:0] io_in_1_rsp_bits_data,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_in_1_rsp_bits_last,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_in_1_rsp_bits_err,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_out_aw_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_out_aw_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [31:0] io_out_aw_bits_awaddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [1:0]  io_out_aw_bits_awid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [7:0]  io_out_aw_bits_awlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [2:0]  io_out_aw_bits_awsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [1:0]  io_out_aw_bits_awburst,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_out_aw_bits_awlock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [3:0]  io_out_aw_bits_awcache,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [2:0]  io_out_aw_bits_awprot,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_out_w_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_out_w_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [31:0] io_out_w_bits_wdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [3:0]  io_out_w_bits_wstrb,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_out_w_bits_wlast,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_out_b_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_out_b_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [1:0]  io_out_b_bits_bresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
                io_out_b_bits_bid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_out_ar_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_out_ar_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [31:0] io_out_ar_bits_araddr,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [1:0]  io_out_ar_bits_arid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [7:0]  io_out_ar_bits_arlen,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [2:0]  io_out_ar_bits_arsize,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [1:0]  io_out_ar_bits_arburst,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_out_ar_bits_arlock,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [3:0]  io_out_ar_bits_arcache,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output [2:0]  io_out_ar_bits_arprot,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  output        io_out_r_ready,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_out_r_valid,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [1:0]  io_out_r_bits_rresp,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [31:0] io_out_r_bits_rdata,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input         io_out_r_bits_rlast,	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
  input  [1:0]  io_out_r_bits_rid	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:18:14]
);

  crossbarCache xbarBridge (	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:23:26]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_0_req_ready     (io_in_0_req_ready),
    .io_in_0_req_valid     (io_in_0_req_valid),
    .io_in_0_req_bits_addr (io_in_0_req_bits_addr),
    .io_in_0_req_bits_data (io_in_0_req_bits_data),
    .io_in_0_req_bits_wen  (io_in_0_req_bits_wen),
    .io_in_0_req_bits_mask (io_in_0_req_bits_mask),
    .io_in_0_req_bits_len  (io_in_0_req_bits_len),
    .io_in_0_req_bits_size (io_in_0_req_bits_size),
    .io_in_0_req_bits_last (io_in_0_req_bits_last),
    .io_in_0_rsp_ready     (io_in_0_rsp_ready),
    .io_in_0_rsp_valid     (io_in_0_rsp_valid),
    .io_in_0_rsp_bits_data (io_in_0_rsp_bits_data),
    .io_in_0_rsp_bits_last (io_in_0_rsp_bits_last),
    .io_in_0_rsp_bits_err  (io_in_0_rsp_bits_err),
    .io_in_1_req_ready     (io_in_1_req_ready),
    .io_in_1_req_valid     (io_in_1_req_valid),
    .io_in_1_req_bits_addr (io_in_1_req_bits_addr),
    .io_in_1_req_bits_data (io_in_1_req_bits_data),
    .io_in_1_req_bits_wen  (io_in_1_req_bits_wen),
    .io_in_1_req_bits_mask (io_in_1_req_bits_mask),
    .io_in_1_req_bits_len  (io_in_1_req_bits_len),
    .io_in_1_req_bits_size (io_in_1_req_bits_size),
    .io_in_1_req_bits_last (io_in_1_req_bits_last),
    .io_in_1_rsp_ready     (io_in_1_rsp_ready),
    .io_in_1_rsp_valid     (io_in_1_rsp_valid),
    .io_in_1_rsp_bits_data (io_in_1_rsp_bits_data),
    .io_in_1_rsp_bits_last (io_in_1_rsp_bits_last),
    .io_in_1_rsp_bits_err  (io_in_1_rsp_bits_err),
    .io_out_aw_ready       (io_out_aw_ready),
    .io_out_aw_valid       (io_out_aw_valid),
    .io_out_aw_bits_awaddr (io_out_aw_bits_awaddr),
    .io_out_aw_bits_awlen  (io_out_aw_bits_awlen),
    .io_out_aw_bits_awsize (io_out_aw_bits_awsize),
    .io_out_w_ready        (io_out_w_ready),
    .io_out_w_valid        (io_out_w_valid),
    .io_out_w_bits_wdata   (io_out_w_bits_wdata),
    .io_out_w_bits_wstrb   (io_out_w_bits_wstrb),
    .io_out_w_bits_wlast   (io_out_w_bits_wlast),
    .io_out_b_ready        (io_out_b_ready),
    .io_out_b_valid        (io_out_b_valid),
    .io_out_b_bits_bresp   (io_out_b_bits_bresp),
    .io_out_ar_ready       (io_out_ar_ready),
    .io_out_ar_valid       (io_out_ar_valid),
    .io_out_ar_bits_araddr (io_out_ar_bits_araddr),
    .io_out_ar_bits_arlen  (io_out_ar_bits_arlen),
    .io_out_ar_bits_arsize (io_out_ar_bits_arsize),
    .io_out_r_ready        (io_out_r_ready),
    .io_out_r_valid        (io_out_r_valid),
    .io_out_r_bits_rresp   (io_out_r_bits_rresp),
    .io_out_r_bits_rdata   (io_out_r_bits_rdata),
    .io_out_r_bits_rlast   (io_out_r_bits_rlast)
  );	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:23:26]
  assign io_out_aw_bits_awid = 2'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
  assign io_out_aw_bits_awburst = 2'h1;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
  assign io_out_aw_bits_awlock = 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
  assign io_out_aw_bits_awcache = 4'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
  assign io_out_aw_bits_awprot = 3'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
  assign io_out_ar_bits_arid = 2'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
  assign io_out_ar_bits_arburst = 2'h1;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
  assign io_out_ar_bits_arlock = 1'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
  assign io_out_ar_bits_arcache = 4'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
  assign io_out_ar_bits_arprot = 3'h0;	// @[home/chenzewei1/ict_project/core/cl1_core/cl1/src/scala/StandaloneBridge.scala:17:7, :23:26]
endmodule
